baseURL = "https://blog.takasing.net/"
languageCode = "en-us"
title = "T#.log"
paginate = 10
theme = "hugo-minimalist-theme"
hasCJKLanguage = "true"

[params]
    site_author = "Takashi Toyofuku"
    site_description = "Engineer, love music, hot spring."
    images = ["icon.jpg"]
    location = "Tokyo, Japan"
    # Link custom assets relative to /static
    avatar = "icon.jpg"
    header_background = "header.jpg"
    header_title = "T#.log"
    copyright = "Powered by [Hugo](https://gohugo.io)."
    custom_css = ['custom.css']
    custom_js  = []
    introduction = """Engineer & PdM <br>
    複雑な仕様をシンプルな仕様に落とし込んで問題解決することが得意です。
    <br>
    """

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-19958120-8"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "takasing_"
    facebook  = ""
    linkedin  = "takasing"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "takasing"
    gplus     = ""
