# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /home/circleci/blog.takasing.net
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: update submodule
          command: git submodule sync && git submodule update --init
      - run:
          name: build my site
          command: hugo
      - save_cache:
          key: public-{{ epoch }}
          paths:
            - ./public

  approve:
    working_directory: /home/circleci/blog.takasing.net
    machine: true
    steps:
      - run:
          name: noope
          command: echo noope

  deploy:
    working_directory: /home/circleci/blog.takasing.net
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          key: public
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install tools
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: deploy my site
          command: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
