# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
      
    working_directory: ~/takasing.net
    steps:
      - checkout
      - run:
          name: install hugo
          command: go get -v github.com/gohugoio/hugo

      # specify any bash command here prefixed with `run: `
      #- run: go get -v -t -d ./...
      #- run: go test -v ./...
